CREATE TABLE IF NOT EXIST toc (
  _id INTEGER PRIMARY KEY,
  title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXIST paragraph (
  _id INTEGER PRIMARY KEY,
  content TEXT NOT NULL,
  order INTEGER NOT NULL,
  toc_id INTEGER NOT NULL,
  CONSTRAINT FK_TOC_PARAGRAPH  FOREIGN KEY(toc_id)
    REFERENCES toc(_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXIST prayer (
  _id INTEGER PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  toc_id INTEGER NOT NULL,
  CONSTRAINT FK_TOC_PRAYER FOREIGN KEY(toc_id)
  	REFERENCES toc(_id) ON DELETE CASCADE
)