CREATE TABLE IF NOT EXISTS toc (
  _id INTEGER PRIMARY KEY,
  title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS paragraph (
  _id INTEGER PRIMARY KEY,
  toc_id INTEGER NOT NULL,
  ordinal INTEGER NOT NULL,
  content TEXT NOT NULL,
  CONSTRAINT FK_TOC_PARAGRAPH  FOREIGN KEY(toc_id)
    REFERENCES toc(_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS prayer (
  _id INTEGER PRIMARY KEY,
  toc_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  CONSTRAINT FK_TOC_PRAYER FOREIGN KEY(toc_id)
  	REFERENCES toc(_id) ON DELETE CASCADE
)